"""Workload estimation and semester packing.

The number of semesters a programme needs is not a preference — it falls out of
how much material the books actually contain against how many hours a semester
has. This module does that arithmetic explicitly so the planner can quote it as
the reason for its decision.

Estimation is deterministic and shows its inputs: pages of cited evidence,
declared difficulty, and a self-study ratio. ``WorkloadEstimate.basis`` spells
out the calculation for anyone checking the plan.
"""

from __future__ import annotations

import math

from pydantic import BaseModel, Field

from planning.overlap import Topic

#: Contact hours generated by one page of source material.
HOURS_PER_PAGE = 0.6
#: Multiplier applied per difficulty point above 1.
DIFFICULTY_STEP = 0.25
#: Self-study hours expected per contact hour.
SELF_STUDY_RATIO = 1.5
#: Floor so a thin but real topic still occupies a slot.
MIN_CONTACT_HOURS = 1.0
#: Default hours a single semester can absorb.
DEFAULT_SEMESTER_CAPACITY_HOURS = 120.0


class WorkloadEstimate(BaseModel):
    """Hours for one topic, with the arithmetic that produced them."""

    topic_id: str
    title: str
    pages: int = Field(ge=1)
    difficulty: int = Field(ge=1, le=5)
    contact_hours: float = Field(gt=0)
    self_study_hours: float = Field(ge=0)
    total_hours: float = Field(gt=0)
    basis: str


def estimate_topic(
    topic: Topic,
    *,
    hours_per_page: float = HOURS_PER_PAGE,
    difficulty_step: float = DIFFICULTY_STEP,
    self_study_ratio: float = SELF_STUDY_RATIO,
    min_contact_hours: float = MIN_CONTACT_HOURS,
) -> WorkloadEstimate:
    """Estimate the teaching load of one topic from its cited evidence."""
    pages = topic.page_span()
    difficulty_multiplier = 1.0 + difficulty_step * (topic.difficulty - 1)
    contact = max(min_contact_hours, round(pages * hours_per_page * difficulty_multiplier, 2))
    self_study = round(contact * self_study_ratio, 2)

    return WorkloadEstimate(
        topic_id=topic.topic_id,
        title=topic.title,
        pages=pages,
        difficulty=topic.difficulty,
        contact_hours=contact,
        self_study_hours=self_study,
        total_hours=round(contact + self_study, 2),
        basis=(
            f"{pages} cited page(s) x {hours_per_page} h/page x {difficulty_multiplier:.2f} "
            f"(difficulty {topic.difficulty}) = {contact} contact h; "
            f"+{self_study_ratio:g}x self-study = {round(contact + self_study, 2)} total h"
        ),
    )


def estimate_all(topics: list[Topic], **kwargs) -> dict[str, WorkloadEstimate]:
    return {topic.topic_id: estimate_topic(topic, **kwargs) for topic in topics}


def required_semesters(
    estimates: dict[str, WorkloadEstimate], *, capacity_hours: float
) -> int:
    """Lower bound on semesters purely from total hours against capacity."""
    if capacity_hours <= 0:
        raise ValueError("capacity_hours must be positive")
    total = sum(item.total_hours for item in estimates.values())
    if total <= 0:
        return 1
    return max(1, math.ceil(round(total / capacity_hours, 6)))


def pack_semesters(
    order: list[str],
    estimates: dict[str, WorkloadEstimate],
    graph: dict[str, list[str]],
    *,
    capacity_hours: float = DEFAULT_SEMESTER_CAPACITY_HOURS,
    max_semesters: int = 8,
    keep_together: list[tuple[str, str]] | None = None,
) -> list[list[str]]:
    """Fill semesters in teaching order without breaking prerequisites.

    A topic starts a new semester when the current one is full, or when one of
    its prerequisites is already scheduled in the semester being filled — a
    prerequisite taught in the same semester gives the student no time to learn
    it first.

    The last semester absorbs any overflow once ``max_semesters`` is reached;
    the planner reports that as an over-capacity decision rather than dropping
    material.
    """
    if capacity_hours <= 0:
        raise ValueError("capacity_hours must be positive")
    if max_semesters < 1:
        raise ValueError("max_semesters must be at least 1")

    pairs = {frozenset(pair) for pair in (keep_together or [])}
    semesters: list[list[str]] = [[]]
    hours = [0.0]
    placed_in: dict[str, int] = {}

    for topic_id in order:
        estimate = estimates.get(topic_id)
        if estimate is None:
            continue
        current = len(semesters) - 1

        prerequisite_clash = any(
            placed_in.get(parent) == current for parent in graph.get(topic_id, [])
        )
        over_capacity = semesters[current] and hours[current] + estimate.total_hours > capacity_hours
        pinned = any(
            frozenset((topic_id, other)) in pairs for other in semesters[current]
        )

        if prerequisite_clash or (over_capacity and not pinned):
            if len(semesters) < max_semesters:
                semesters.append([])
                hours.append(0.0)
                current = len(semesters) - 1

        semesters[current].append(topic_id)
        hours[current] += estimate.total_hours
        placed_in[topic_id] = current

    return [semester for semester in semesters if semester]


def semester_hours(semester: list[str], estimates: dict[str, WorkloadEstimate]) -> float:
    return round(sum(estimates[topic_id].total_hours for topic_id in semester if topic_id in estimates), 2)


__all__ = [
    "DEFAULT_SEMESTER_CAPACITY_HOURS",
    "DIFFICULTY_STEP",
    "HOURS_PER_PAGE",
    "MIN_CONTACT_HOURS",
    "SELF_STUDY_RATIO",
    "WorkloadEstimate",
    "estimate_all",
    "estimate_topic",
    "pack_semesters",
    "required_semesters",
    "semester_hours",
]
